[package]
name = "rgit-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rgit-core.workspace = true
rgit-git.workspace = true

tokio.workspace = true
sqlx.workspace = true
anyhow.workspace = true
thiserror.workspace = true
base64.workspace = true
serde_json.workspace = true
